require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.1
  NewCops: enable

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 9

Documentation:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 15

Lint/ConstantDefinitionInBlock:
  Enabled: false
